export const DEVICE_WIDTH = "DEVICE_WIDTH";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const LOGIN_PROCESS = "LOGIN_PROCESS";
export const LOAD_USER = "LOAD_USER";
export const SYSTEM_SEARCH = "SYSTEM_SEARCH";
export const LOAD_SYSTEM = "LOAD_SYSTEM";
export const LOAD_SYSTEM_STOCK = "LOAD_SYSTEM_STOCK";
